services:
  webui:
    image: scraper-webui-image
    container_name: scraper-webui
    build:
      context: ./WebUI
      args:
        # The backend url is only needed while building the image.
        # Please insert only the path of the API endpoint
        # The host will be automatically manage by nginx configuration.
        # It will be replaced with the dns name of the 'server' service
        - VITE_BACKEND_API=/api/v1/live
    pull_policy: never
    environment:
      - WEBUI_PORT=3000
    ports:
      - "3000:80"
    networks:
      - scraper_network
    restart: unless-stopped

  server:
    image: scraper-server-image
    container_name: scraper-server
    build:
      context: ./Server
      dockerfile: Dockerfile
    pull_policy: never
    environment:
      - SERVER_PORT=${SERVER_PORT:-8000}
    # if you want to access the API outside this scraper's intranet, you can map the ports to the host machine's network
    # otherwise, you can remove this port mapping configuration.
    ports:
      - "${SERVER_PORT:-8000}:${SERVER_PORT:-8000}"
    networks:
      - scraper_network
    restart: unless-stopped

networks:
  scraper_network:
    driver: bridge
